# Generated by Django 5.1.4 on 2025-03-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('email_placeholder', models.CharField(default='Type your email to get access', max_length=255)),
                ('button_text', models.CharField(default='Try For Free', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
            ],
        ),
    ]
