# Generated by Django 5.1.4 on 2025-03-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('navigation_items', models.JSONField(default=list)),
                ('has_pricing', models.BooleanField(default=True)),
                ('has_dashboard', models.BooleanField(default=True)),
                ('has_auth_buttons', models.BooleanField(default=True)),
                ('footer_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('social_links', models.JSONField(default=list)),
                ('footer_links', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PaypalSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Complete Your Payment with PayPal', max_length=255)),
                ('description', models.TextField(default='Select a plan and pay securely via PayPal.')),
                ('success_message', models.CharField(default='🎉 Congratulations! Your payment was successful!', max_length=255)),
                ('redirect_url', models.URLField(default='/dashboard')),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('plans', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('solutions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='StatsSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bullet_points', models.JSONField(default=list)),
                ('button_text', models.CharField(default='See EngageIQ in Action', max_length=50)),
                ('stats', models.JSONField(default=list)),
                ('main_image', models.CharField(blank=True, max_length=255, null=True)),
                ('left_image', models.CharField(blank=True, max_length=255, null=True)),
                ('right_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Available On-Demand & Live', max_length=100)),
                ('main_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('main_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('modules', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(default='Try EngageIQ Free', max_length=50)),
                ('features', models.JSONField(default=list)),
                ('feature_icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='background_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
