# Generated by Django 5.1.4 on 2025-03-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0002_layoutcontent_paypalsectioncontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('tooltip_content', models.JSONField(default=dict)),
                ('main_image', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
