# Generated by Django 5.1.4 on 2025-03-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0003_dashboardcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardcontent',
            old_name='icon_image',
            new_name='secondary_image',
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
