# Generated by Django 5.1.4 on 2025-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0004_rename_icon_image_dashboardcontent_secondary_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statssectioncontent',
            name='engage_button_text',
            field=models.CharField(default='Try EngageIQ Free', max_length=50),
        ),
        migrations.AddField(
            model_name='statssectioncontent',
            name='engage_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statssectioncontent',
            name='engage_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statssectioncontent',
            name='sales_messaging_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statssectioncontent',
            name='sales_messaging_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
