# Generated by Django 5.1.4 on 2025-03-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0005_statssectioncontent_engage_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutcontent',
            name='about_us_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layoutcontent',
            name='about_us_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='layoutcontent',
            name='contact_info',
            field=models.JSONField(default=dict),
        ),
    ]
