# Generated by Django 5.1.4 on 2025-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0006_layoutcontent_about_us_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalsectioncontent',
            name='heading',
            field=models.CharField(default='Choose The Best Pricing Plan for Your Business', max_length=255),
        ),
    ]
