# Generated by Django 5.1.4 on 2025-03-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0007_paypalsectioncontent_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalsectioncontent',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='paypalsectioncontent',
            name='plans',
        ),
    ]
