# Generated by Django 5.1.4 on 2025-03-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0008_remove_paypalsectioncontent_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalsectioncontent',
            name='redirect_url',
        ),
    ]
