# Generated by Django 5.1.4 on 2025-03-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0009_remove_paypalsectioncontent_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectioncontent',
            name='blacklogo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosectioncontent',
            name='hero_bottom_right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosectioncontent',
            name='hero_left',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosectioncontent',
            name='hero_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosectioncontent',
            name='hero_top_right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosectioncontent',
            name='tick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='email_placeholder',
            field=models.CharField(default='Enter your email', max_length=255),
        ),
    ]
