# Generated by Django 5.1.4 on 2025-03-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0010_herosectioncontent_blacklogo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutcontent',
            name='about_us_description',
        ),
        migrations.RemoveField(
            model_name='layoutcontent',
            name='about_us_images',
        ),
        migrations.RemoveField(
            model_name='layoutcontent',
            name='contact_info',
        ),
    ]
