# Generated by Django 5.1.4 on 2025-03-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0011_remove_layoutcontent_about_us_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='secondary_image',
        ),
    ]
