# Generated by Django 5.1.4 on 2025-03-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0012_remove_dashboardcontent_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosectioncontent',
            name='main_thumbnail',
        ),
        migrations.RemoveField(
            model_name='videosectioncontent',
            name='main_video',
        ),
    ]
