# Generated by Django 5.1.4 on 2025-03-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0013_remove_videosectioncontent_main_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosectioncontent',
            name='button_text',
        ),
    ]
