# Generated by Django 5.1.4 on 2025-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0014_remove_herosectioncontent_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectioncontent',
            name='subheading',
            field=models.CharField(default='Proven and Built on Human Decision Science.', max_length=255),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='blacklogo',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_bottom_right',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_left',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_section',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_top_right',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='tick',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
