# Generated by Django 5.1.4 on 2025-03-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0015_herosectioncontent_subheading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosectioncontent',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='herosectioncontent',
            name='hero_image',
        ),
    ]
