# Generated by Django 5.1.4 on 2025-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0016_remove_herosectioncontent_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingsectioncontent',
            name='feature_icon',
            field=models.ImageField(blank=True, null=True, upload_to='feature_icons/'),
        ),
    ]
