# Generated by Django 5.1.4 on 2025-03-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0018_remove_workingsectioncontent_features_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingsectioncontent',
            name='feature_icon',
            field=models.ImageField(blank=True, null=True, upload_to='work/'),
        ),
    ]
