# Generated by Django 5.1.4 on 2025-03-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0019_alter_workingsectioncontent_feature_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionsectioncontent',
            name='solutions',
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='solution/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='content_manage_app.solutionsectioncontent')),
            ],
        ),
    ]
