# Generated by Django 5.1.4 on 2025-03-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0020_remove_solutionsectioncontent_solutions_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statssectioncontent',
            name='bullet_points',
        ),
        migrations.RemoveField(
            model_name='statssectioncontent',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='statssectioncontent',
            name='engage_button_text',
        ),
        migrations.RemoveField(
            model_name='statssectioncontent',
            name='stats',
        ),
        migrations.AlterField(
            model_name='statssectioncontent',
            name='left_image',
            field=models.ImageField(blank=True, null=True, upload_to='stats/'),
        ),
        migrations.AlterField(
            model_name='statssectioncontent',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='stats/'),
        ),
        migrations.AlterField(
            model_name='statssectioncontent',
            name='right_image',
            field=models.ImageField(blank=True, null=True, upload_to='stats/'),
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='content_manage_app.statssectioncontent')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content_manage_app.statssectioncontent')),
            ],
        ),
    ]
