# Generated by Django 5.1.4 on 2025-03-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0021_remove_statssectioncontent_bullet_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statssectioncontent',
            name='engage_description',
        ),
        migrations.RemoveField(
            model_name='statssectioncontent',
            name='engage_title',
        ),
    ]
