# Generated by Django 5.1.4 on 2025-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0022_remove_statssectioncontent_engage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosectioncontent',
            name='blacklogo',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_bottom_right',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_left',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_section',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='hero_top_right',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosectioncontent',
            name='tick',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
