# Generated by Django 5.1.4 on 2025-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0023_alter_herosectioncontent_blacklogo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='subheading',
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='border',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='boy',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='edit',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='home',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='training',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/'),
        ),
        migrations.AddField(
            model_name='dashboardcontent',
            name='usage',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/'),
        ),
    ]
