# Generated by Django 5.1.4 on 2025-03-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0024_remove_dashboardcontent_subheading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='tooltip_content',
        ),
        migrations.CreateModel(
            name='Tooltip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooltips', to='content_manage_app.dashboardcontent')),
            ],
        ),
    ]
