# Generated by Django 5.1.4 on 2025-03-24 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0025_remove_dashboardcontent_tooltip_content_tooltip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcontent',
            name='boy',
        ),
    ]
