# Generated by Django 5.1.4 on 2025-03-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0027_remove_videosectioncontent_modules_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosectioncontent',
            name='button_text',
        ),
    ]
