# Generated by Django 5.1.4 on 2025-03-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0028_remove_videosectioncontent_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutcontent',
            name='footer_links',
        ),
        migrations.RemoveField(
            model_name='layoutcontent',
            name='has_auth_buttons',
        ),
        migrations.RemoveField(
            model_name='layoutcontent',
            name='has_dashboard',
        ),
        migrations.RemoveField(
            model_name='layoutcontent',
            name='has_pricing',
        ),
        migrations.RemoveField(
            model_name='layoutcontent',
            name='navigation_items',
        ),
        migrations.RemoveField(
            model_name='layoutcontent',
            name='social_links',
        ),
        migrations.AlterField(
            model_name='layoutcontent',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='layout/'),
        ),
        migrations.AlterField(
            model_name='layoutcontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='layout/'),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='content_manage_app.layoutcontent')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='content_manage_app.layoutcontent')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='content_manage_app.layoutcontent')),
            ],
        ),
    ]
