# Generated by Django 5.1.4 on 2025-03-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0029_remove_layoutcontent_footer_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutcontent',
            name='footer_logo',
        ),
    ]
