# Generated by Django 5.1.4 on 2025-03-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0030_remove_layoutcontent_footer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='url',
            field=models.URLField(default='/'),
        ),
    ]
