# Generated by Django 5.1.4 on 2025-03-24 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0031_navigationitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='heading',
        ),
        migrations.AddField(
            model_name='layoutcontent',
            name='social_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='content_manage_app.layoutcontent')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='content_manage_app.layoutcontent')),
            ],
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
