# Generated by Django 5.1.4 on 2025-03-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0032_remove_sociallink_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutcontent',
            name='social_heading',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
