# Generated by Django 5.1.4 on 2025-03-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0034_remove_sociallink_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/')),
            ],
        ),
    ]
