# Generated by Django 5.1.4 on 2025-04-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manage_app', '0036_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
