# Generated by Django 5.1.4 on 2025-02-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='document_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
