# Generated by Django 5.1.4 on 2025-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0002_emailmessage_document_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.AddField(
            model_name='apiusage',
            name='total_email_sent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='email_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='token_limit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='used_api_calls',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='used_emails',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='used_tokens',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='total_api_calls_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='total_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apiusage',
            name='total_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled')], default='inactive', max_length=50),
        ),
    ]
