# Generated by Django 5.1.4 on 2025-02-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0003_remove_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
