# Generated by Django 5.1.4 on 2025-02-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0004_subscriptionplan_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='total_api_calls_count',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='api_call_limit',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='used_api_calls',
        ),
    ]
