# Generated by Django 5.1.4 on 2025-02-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0005_remove_apiusage_total_api_calls_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='document_content',
        ),
    ]
