# Generated by Django 5.1.4 on 2025-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0006_remove_emailmessage_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
