# Generated by Django 5.1.4 on 2025-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0007_subscriptionplan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_days',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='used_emails',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='used_tokens',
        ),
        migrations.AddField(
            model_name='apiusage',
            name='total_used_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
