# Generated by Django 5.1.4 on 2025-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0008_remove_subscriptionplan_trial_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='total_email_sent',
        ),
        migrations.AddField(
            model_name='apiusage',
            name='total_api_call_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
