# Generated by Django 5.1.4 on 2025-03-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0012_billingrecord_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='duration',
            new_name='billing_cycle',
        ),
    ]
