# Generated by Django 5.1.4 on 2025-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0014_alter_usersubscription_billing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10, null=True),
        ),
    ]
