# Generated by Django 5.1.4 on 2025-03-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0016_alter_billingrecord_billing_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='billing_cycle',
            new_name='duration',
        ),
    ]
