# Generated by Django 5.1.4 on 2025-04-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0017_rename_billing_cycle_subscriptionplan_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='email_limit',
            new_name='Queries',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='token_limit',
        ),
    ]
