# Generated by Django 5.1.4 on 2025-04-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0018_rename_email_limit_subscriptionplan_queries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='Seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='Target_Audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
