# Generated by Django 5.1.4 on 2025-04-11 17:25

import engageiq_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0019_subscriptionplan_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=engageiq_app.models.subscription_image_upload_path),
        ),
    ]
