# Generated by Django 5.1.4 on 2025-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0020_subscriptionplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='contact_us',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='footer_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='image_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
