# Generated by Django 5.1.4 on 2025-04-11 18:19

import engageiq_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0021_subscriptionplan_contact_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=engageiq_app.models.enterprise_logo_upload_path),
        ),
    ]
