# Generated by Django 5.1.4 on 2025-04-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engageiq_app', '0022_subscriptionplan_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='total_input_tokens',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='total_output_tokens',
        ),
        migrations.RemoveField(
            model_name='apiusage',
            name='total_used_tokens',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='input_tokens',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='output_tokens',
        ),
    ]
