# Generated by Django 5.1.4 on 2025-03-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_category_post_image_post_is_deleted_post_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
