# Generated by Django 5.1.4 on 2025-03-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='headings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
