# Generated by Django 5.1.4 on 2025-03-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_additional_image_post_headings_post_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='additional_image',
        ),
        migrations.AddField(
            model_name='post',
            name='additional_images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='headings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.JSONField(default=list),
        ),
    ]
