# Generated by Django 5.1.4 on 2025-03-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_remove_post_additional_images_alter_post_headings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headings',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='links',
        ),
    ]
