# Generated by Django 5.1.4 on 2025-03-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
