# Generated by Django 5.1.4 on 2025-03-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_remove_post_categories_remove_post_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='blog_app.post')),
            ],
        ),
        migrations.RemoveField(
            model_name='additionalimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='heading',
            name='post',
        ),
        migrations.RemoveField(
            model_name='link',
            name='post',
        ),
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
