# Generated by Django 5.1.4 on 2025-03-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
