# Generated by Django 5.1.4 on 2025-03-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_remove_post_image_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='post',
        ),
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='link',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='PostContent',
        ),
    ]
