# Generated by Django 5.1.4 on 2025-03-27 17:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_remove_heading_post_remove_image_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sections',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
