# Generated by Django 5.1.4 on 2025-03-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_alter_post_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
