# Generated by Django 5.1.4 on 2025-03-27 21:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_remove_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sections',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
